In [1]:
# Element-wise operations: applied independently to each entry in the tensors

In [2]:
# Broadcasting: smaller tensor will be broadcasted to match the shape of the larger tensor

In [2]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10)) # y gets broadcasted, virtually comes (64, 3, 32, 10)
z = np.maximum(x, y)
print(z.shape)

(64, 3, 32, 10)


In [3]:
# Tensor dot (product): combines entries in the input tensors

In [4]:
# Dot prodect between 2 vectores

# vectors with the same number of elements are compatible
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.dot(x,y)) # 1*4 + 2*5 + 3*6 = 32

# Symmetric
np.dot(x,y) == np.dot(y,x)

32


True

In [5]:
# Dot prodect between a matrix and a vector

x = np.array([[1,2],
              [3,4],
              [5,6]])
y = np.array([2,2])
print(np.dot(x,y)) # [1*2+2*2=6, 3*2+4*2=14, 5*2+6*2=22]

# No longer symmteric
x = np.array([[1,2],
              [3,4]])
y = np.array([2,2])
np.dot(x,y) == np.dot(y,x)

[ 6 14 22]


array([False, False])

In [6]:
# Dot prodect between 2 matrices

# Compatible only if x.shape[1] == y.shape[0]
x = np.array([[1,2],
              [3,4],
              [5,6]])
y = np.array([[1,2,3],
              [4,5,6]])
assert x.shape[1] == y.shape[0]
np.dot(x,y)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [7]:
# An example of non-compatible dot operations

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
y = np.array([[1,2,3],
              [4,5,6]])
assert x.shape[1] == y.shape[0]
np.dot(x,y)

AssertionError: 

In [8]:
# dot product between higher-d tensors, following the same rules for shape compatibility
# (a, b, c, d) . (d,) -> (a, b, c)
# (a, b, c, d) . (d, e) -> (a, b, c, e)

In [19]:
# Tensor reshaping
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])

print(x.shape)

x = x.reshape(6,1)
x

(3, 2)


array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [21]:
x = x.reshape(2,3)
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [24]:
x = np.zeros((300,20))
x.shape

(300, 20)

In [28]:
# Transposition: swapping axis so x[i,:] becomes x[:,i]
y = np.transpose(x)
print(x.shape)
print(y.shape)

(20, 300)
(300, 20)
